Sohee/1
hanhae-plus-be-fifteen-team/assignments pull request #4
Opened 2024-03-19 11:31 UTC by shpark-personal

2024-03-19 12:14 UTC, JeHwanYoo commented on sohee/week-1/.prettierrc
> +}
궁금한점이 있습니다! 혹시 yaml 형식을 vscode 등에서 인식하지 못하는 걸까요?

2024-03-19 12:23 UTC, shpark-personal commented on sohee/week-1/.prettierrc
> +}
yaml 언어지원 확장 팩을 설치하면 되는 것 같습니다!

2024-03-19 12:27 UTC, JeHwanYoo requested changes

2024-03-19 12:27 UTC, JeHwanYoo commented on sohee/week-1/src/point/point.service.ts
> +      console.log('포인트가 부족하여 사용할 수 없습니다.')
추후에 BadRequest (400) 를 보낼 수 있도록 에러를 throw 하면 어떠신가요?

저같은 경우엔, 서비스 레이어에서 바로 BadRequestException 을 던지기보다는 커스텀 Error 를 던지고,

Controller 가 표현계층의 역할을 하므로, 이곳에서 커스텀 에러를 파악하고, BadRequestException 을 최종적으로 던지는 편입니다.

또한, 에러 스택을 만들기 위한 2022년도에 추가된 문법인 [cause](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) 도 확인해보시면 도움이 되실거 같습니다.

2024-03-19 12:27 UTC, JeHwanYoo commented on sohee/week-1/.prettierrc
> +}
아하 그렇군요!

2024-03-19 12:31 UTC, JeHwanYoo requested changes

2024-03-19 12:31 UTC, JeHwanYoo commented on sohee/week-1/src/point/point.service.ts
> +    if (prevAmount - amount < 0) {
validation 이 필요한 코드의 경우 저는 `it.todo` 로 먼저 테스트케이스를 생성한 뒤에, 해당 테스트 코드를 작성하기 전까지 validation 을 하지 않는 편이에요! 물론 실제 업무에선 테스트코드 없이 먼저 구현해야하는 경우도 있지만, TDD 학습기간에는 테스트 코드를 먼저 작성하여 유의미한 테스트 커버리지를 높이는 연습을 해보시면 좋을거 같아요.

2024-03-19 12:37 UTC, shpark-personal commented on sohee/week-1/src/point/point.service.ts
> +      console.log('포인트가 부족하여 사용할 수 없습니다.')
Error에 대한 코드와 test case도 더 추가해보겠습니다~ 감사합니다!

2024-03-20 13:56 UTC, JeHwanYoo commented on sohee/week-1/package.json
> +    "start-dev": "nest start --watch",
보통 - 컨벤션을 사용하시나요?

일반적으로는 콜론(:)을 많이 사용하는거 같아요.

2024-03-20 13:57 UTC, JeHwanYoo approved these changes
동시성 처리를 한번 고려해보시면 좋을거 같아요 💪

2024-03-21 02:18 UTC, shpark-personal commented on sohee/week-1/package.json
> +    "start-dev": "nest start --watch",
: 사용 시, "파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다." 가 뜨네요

2024-03-21 02:19 UTC, merged