Jeonghyo/1
hanhae-plus-be-fifteen-team/assignments pull request #5
Opened 2024-03-19 12:07 UTC by JHKANG9140

2024-03-19 12:32 UTC, shpark-personal approved these changes

2024-03-19 12:32 UTC, shpark-personal commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +    });
각 test 전에 setting하는 방법이 이거였군요!!!

2024-03-19 12:35 UTC, JeHwanYoo requested changes

2024-03-19 12:35 UTC, JeHwanYoo commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +    });
입력 테스트라기 단순 조회테스트에 가까운것 같습니다!

유닛테스트에서 beforeEach 에서는 보통 테스트를 준비하기 위한 목적인 코드를 실행합니다.

따라서, service.charge() 를 테스트할 것이기 때문에 it() 안에 위치 해야할거 같습니다.

그리고 데이터베이스 코드를 활용하면 charge() 코드 만으로 조회까지 가능할거 같습니다!

2024-03-19 12:37 UTC, JeHwanYoo commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +    });
우선, 제공받은 데이터베이스 코드는 입력이 끝나면 이후 상태를 바로 조회해서 던져줍니다.

일반적인 DBMS 에서는 보통 그러지 않으니, 저는 보통, insert() 를 한 뒤에 find() 를 같이 하는 편입니다!

2024-03-19 12:44 UTC, JeHwanYoo commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +      expect(userHistory[4].amount).toEqual(4000);
@shpark-personal 네 있어요! [jest each](https://jestjs.io/docs/api#testeachtablename-fn-timeout)

https://www.daleseo.com/jest-each/ 참고해주세요.

2024-03-19 12:54 UTC, shpark-personal commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +      expect(userHistory[4].amount).toEqual(4000);
https://jestjs.io/docs/using-matchers#:~:text=toBe%20uses%20Object.is%20to%20test%20exact%20equality 
object의 비교도 가능하네요!

2024-03-19 12:56 UTC, JHKANG9140 commented on jeonghyo/week-1/src/point/point.service.spec.ts
> +    });
다시 보니 그렇네요. 더 간결하게 테스트하는 방법이 있었는데 생각하지 못했습니다. 감사합니다.

2024-03-20 14:00 UTC, JeHwanYoo commented on jeonghyo/week-1/src/point/point.service.ts
> +        }
히스토리 생성에 실패하면 복구하는 코드를 짜셨군요! 좋습니다 🙌🏻

저는 히스토리에 대한 접근을 다르게 해보려고 하는데요, 예를들어 충전과 히스토리 자체를 분리시키고, 충전 뒤에는 히스토리를 저장해야한다는 것만 큐에 넣어 놓는 겁니다. 그리고 나중에 일괄적으로 히스토리를 저장하려고요! 저장시에 해당 내용이 정말 수행됐는지를 가지고 히스토리를 쓸지 말지 결정할겁니다! 이러면 응답속도가 더 빨라질 수 있을거 같아요.

2024-03-20 14:01 UTC, JeHwanYoo approved these changes
추후에 동시성에 대한 테스트를 추가하시면 될거같아요 💪

2024-03-23 06:43 UTC, merged