Soongyu/1
hanhae-plus-be-fifteen-team/assignments pull request #6
Opened 2024-03-20 01:35 UTC by SGKwon95

2024-03-20 12:39 UTC, JeHwanYoo requested changes

2024-03-20 12:39 UTC, JeHwanYoo commented on soongyu/week-1/src/app.module.ts
> +  providers: [AppService, UserPointService],
AppModule 에 주입하기보다는 PointModule 에 주입하는 것이 더 올바릅니다.

2024-03-20 12:39 UTC, JeHwanYoo commented on soongyu/week-1/src/point/point.service.spec.ts
> +      expect(userPoint.point).toEqual(0)
toMatchObject 로 하면 더 깔끔할것 같습니다.

2024-03-20 14:02 UTC, JeHwanYoo commented
구현이 어디까지 된것인지 간략하게 요약해주시면 이해하는데 도움이 될 것 같습니다!

2024-03-21 11:46 UTC, SGKwon95 commented on soongyu/week-1/src/point/point.service.spec.ts
> +      expect(userPoint.point).toEqual(0)
조언 감사합니다

2024-03-23 06:42 UTC, merged